mvp
AYETATAPIN/OOP pull request #1
Opened 2024-09-11 02:17 UTC by AYETATAPIN

2024-09-11 03:14 UTC, galinabykova requested changes
ещё нужно исправить замечания ревьюдога (комментарии ревьюдог на вкладке Files changed),  сделать скрипт и доказать асимптотику, как указано в задании

2024-09-11 03:14 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/demidov/Main.java
> +public class Main { /** main */
лучше дать этому классу название, связанное с его функциональностью

2024-09-11 03:14 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/demidov/Main.java
> +    public static void swapping(int[] arr, int index, int n) { // SiftDown
не уверена, что это название отображает функциональность метода. Или переменуй, или обоснуй)

2024-09-11 03:14 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/demidov/Main.java
> +    public static int[] heapsort(int[] arr) { // Heap building and sorting
в Java массивы передаются по ссылке, поэтому после выполнения этого метода у тебя и возвращаемое значение, и входной параметр будут отсортированы. Это неочевидное для пользователя поведение.

Предлагаю либо ничего не возвращать из этого метода, либо клонировать массив перед началом работы

2024-09-11 03:14 UTC, galinabykova commented on Task_1_1_1/src/test/java/ru/nsu/demidov/MainTest.java
> +    public void testing_machine() {
хочется, чтобы при запуске кода было видно текстовое описание класса. Это можно достичь, либо разбив этот метод на несколько отдельных, каждому дав осмысленное название, либо используя параметризированные тесты (что по сути синтаксический сахар для предыдущего варианта), либо найти assert/except, который записывает сообщение в лог. **Проще всего разбить тест на несколько, сделай это)** 

Также нужно использовать не Arrays.equals, который является обычным методом, возвращающим булев тип, а assert или except, специальный методы для проверки.
https://junit.org/junit4/javadoc/4.13/org/junit/Assert.html

2024-09-11 03:27 UTC, AYETATAPIN commented on Task_1_1_1/src/main/java/ru/nsu/demidov/Main.java
> +    public static int[] heapsort(int[] arr) { // Heap building and sorting
так я же новый массив возвращаю, а не тот же самый

2024-09-11 03:39 UTC, AYETATAPIN commented on Task_1_1_1/src/main/java/ru/nsu/demidov/Main.java
> +public class Main { /** main */
done

2024-09-11 03:39 UTC, AYETATAPIN commented on Task_1_1_1/src/main/java/ru/nsu/demidov/Main.java
> +    public static void swapping(int[] arr, int index, int n) { // SiftDown
done

2024-09-11 03:39 UTC, AYETATAPIN commented on Task_1_1_1/src/main/java/ru/nsu/demidov/Main.java
> +    public static int[] heapsort(int[] arr) { // Heap building and sorting
done

2024-09-11 03:39 UTC, AYETATAPIN commented on Task_1_1_1/src/test/java/ru/nsu/demidov/MainTest.java
> +    public void testing_machine() {
done

2024-09-11 16:30 UTC, galinabykova requested changes
удали ненужные файлики, папки jquery, legal и тд

2024-09-12 04:28 UTC, galinabykova approved these changes

2024-09-16 09:39 UTC, merged