Task_1_1_2
AYETATAPIN/OOP pull request #2
Opened 2024-09-13 06:24 UTC by AYETATAPIN

2024-09-16 05:12 UTC, galinabykova requested changes
мягкий дедлайн засчитан, но тебе ещё много делать, так что не затягивай

2024-09-16 05:12 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack$Card.class
удали ненужные файлики

2024-09-16 05:12 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
нужно разбить решение на файлы, общее правило "один класс - один файл", могут быть исключения, но в общем так

2024-09-16 05:12 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +        void deckOf36() {
сделай создание колоды в цикле

2024-09-16 05:12 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +        void deckOf52() {
создание колоды в цикле

2024-09-16 05:12 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +        void shuffle() {
есть библиотечный shuffle, лучше использовать его

2024-09-16 05:12 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +            if (score > 21 && currentCard.value == 11) {
магические константы

2024-09-16 05:12 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +    public static void main(String[] args) throws InterruptedException {
этот метод делает слишком много всего, поэтому его трудно читать. Всё время приходится прыгать между уровнями абстракции: так, тут мы раздаём карты и делаем это вот так, а это уже следующая операция... Нужно выделить отдельные задачи в отдельные приватные методы

2024-09-19 03:29 UTC, AYETATAPIN commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack$Card.class
done

2024-09-19 03:29 UTC, AYETATAPIN commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
done

2024-09-19 03:29 UTC, AYETATAPIN commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +        void deckOf52() {
done

2024-09-19 03:29 UTC, AYETATAPIN commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +        void shuffle() {
done

2024-09-19 03:29 UTC, AYETATAPIN commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +            if (score > 21 && currentCard.value == 11) {
done

2024-09-19 03:29 UTC, AYETATAPIN commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack.java
> +    public static void main(String[] args) throws InterruptedException {
done?

2024-09-23 07:06 UTC, galinabykova requested changes

2024-09-23 07:06 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/BlackJack$Card.class
нужно удалить ненужные файлики. Не забудь сделать git rm

2024-09-23 07:06 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/Hand.java
> +    int winningScore = 21;
можно сделать тут final и именовать как константу в нашем стиле кода, то есть WINNING_SCORE

2024-09-23 07:06 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/demidov/Card.java
> +    String name;
сделай все поля в классах приватными (оберни хотя бы гетттерами и сеттерами)

2024-09-23 14:13 UTC, galinabykova approved these changes

2024-09-25 02:22 UTC, AYETATAPIN commented on Task_1_1_2/src/main/java/ru/nsu/demidov/Card.java
> +    String name;
done

2024-09-25 02:22 UTC, merged