Task_1_1_3
AYETATAPIN/OOP pull request #3
Opened 2024-09-26 10:09 UTC by AYETATAPIN

2024-09-26 16:02 UTC, galinabykova requested changes
мягкий засчитан, не забудь тесты и парсер. И не тяни с новой версией, будет ещё минимум одна итерация со значительными изменениями

2024-09-26 16:02 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/demidov/Expression.java
> +    public void ballsParser(String ejaculateballs) {
надо это исправить. Предлагаю убрать values из полей и сделать эту функцию статической с возвращаемым значением HashMap

2024-09-26 16:39 UTC, AYETATAPIN commented on Task_1_1_3/src/main/java/ru/nsu/demidov/Expression.java
> +    public void ballsParser(String ejaculateballs) {
как переменной может быть не дано означивание?

2024-09-26 17:18 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/demidov/Expression.java
> +    public void ballsParser(String ejaculateballs) {
я про переменную из ejaculateballs, вполне, например что-то вроде `(new Value("x")).ejaculateballs("y=2")`

2024-10-02 03:08 UTC, AYETATAPIN commented on Task_1_1_3/src/main/java/ru/nsu/demidov/Expression.java
> +    Map<String, Integer> values;
done

2024-10-02 03:08 UTC, AYETATAPIN commented on Task_1_1_3/src/main/java/ru/nsu/demidov/Add.java
> +package ru.nsu.demidov;
done

2024-10-02 08:46 UTC, AYETATAPIN commented on Task_1_1_3/src/main/java/ru/nsu/demidov/Expression.java
> +    public void ballsParser(String ejaculateballs) {
done?

2024-10-02 08:56 UTC, galinabykova requested changes

2024-10-02 08:56 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/demidov/expressions/Variable.java
> +        Map<String, Integer> values = ballsParser(ejaculateballs);
здесь оно всё равно будет вызываться много раз. Я имела ввиду немного другое, что-то такое
```java
abstract class Expression {
    //...
    
    public double ejaculate(String s) {
        return ejaculate(ballsParser(s));
    }
    
    private HashMap<String, Double> stringToMap(String s) {
        // ...
        return new HashMap<String, Double>();
    }
    
    abstract protected double ejaculate(HashMap<String, Double> dict);
}

class Value extends Expression {
    private String name;
    
    @Override
    protected double ejaculate(HashMap<String, Double> dict) {
        return dict.get(name);
    }
}

class Mul extends Expression {
    private Expression left;
    private Expression right;
    
    @Override
    protected double ejaculate(HashMap<String, Double> dict) {
        return left.ejaculate(dict) + right.ejaculate(dict);
    }
}
```

2024-10-02 08:56 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/demidov/expressions/Add.java
> +    private Expression first;
можно ещё final сделать

2024-10-02 17:30 UTC, merged