Task_1_2_1
AYETATAPIN/OOP pull request #4
Opened 2024-10-13 17:11 UTC by AYETATAPIN

2024-10-14 05:11 UTC, galinabykova requested changes
мягкий засчитан, но ещё много работы, поэтому не затягивай с правками)

2024-10-14 05:11 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/Graph.java
> +    void addVertex(T vertex);
в этой задаче говорится об объектной модели, поэтому хотелось бы, чтобы были хотя бы отдельные классы для вершин и рёбер

2024-10-14 05:11 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/Graph.java
> +    void removeVertex(T vertex) throws Exception;
всё-таки лучше конкретизировать вид исключения

2024-10-14 05:11 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/AdjacencyList.java
> +        BufferedReader input = new BufferedReader(new FileReader(path));
если у тебя будет выброшено исключение, файл никогда не закроется. Используй try catch with recources. А исключение можно после того, как отловишь, дальше пробросить

2024-10-14 05:11 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/AdjacencyMatrix.java
> +    public List<T> toposort() {
у тебя должна быть одна реализация топсорт. Она не должна знать, какой вид графа ей пришёл, то есть это должен быть метод toposort(Graph <T> g) либо в графе (реализация по умолчанию), либо в отдельном классе

2024-10-14 08:11 UTC, AYETATAPIN commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/AdjacencyList.java
> +        BufferedReader input = new BufferedReader(new FileReader(path));
файл закрывается при завершении процесса, я оси сдавал

2024-10-14 09:18 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/AdjacencyList.java
> +        BufferedReader input = new BufferedReader(new FileReader(path));
круто, но вдруг у тебя процесс существует год и за этот год ему надо открывать очень много файлов? в какой-то момент дескрипторы могут закончиться

2024-10-18 06:04 UTC, AYETATAPIN commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/Graph.java
> +    void addVertex(T vertex);
nene

2024-10-18 06:04 UTC, AYETATAPIN commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/Graph.java
> +    void removeVertex(T vertex) throws Exception;
done

2024-10-18 07:54 UTC, AYETATAPIN commented on Task_1_2_1/src/main/java/ru/nsu/demidov/graph/AdjacencyList.java
> +        BufferedReader input = new BufferedReader(new FileReader(path));
done

2024-10-19 09:00 UTC, galinabykova requested changes

2024-11-03 10:34 UTC, merged