Task_1_2_2
AYETATAPIN/OOP pull request #6
Opened 2024-10-27 15:27 UTC by AYETATAPIN

2024-10-28 02:24 UTC, galinabykova requested changes

2024-10-28 02:24 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
сделай тест, в котором сравниваешь две хэш-таблицы с разными типами K и V

2024-10-28 02:24 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +        modCount++;
мне кажется, эту строчку можно было бы выделить в отдельный приватный метод. Эту строчку нужно выполнять каждый раз, когда хэш-таблица изменилась и у неё очень много вхождений. Можно предположить, что при поддержке хэш-таблицы будут добавляться другие действия, который нужно выполнить каждый раз, когда будут происходить изменения. Если бы этот код был вынесен в отдельный метод, было бы проще поменять код при такой ситуации. Также "хэш-таблица поменялась" довольно осмысленное атомарное действие

2024-10-28 02:24 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +        modCount++;
но ты можешь это оспорить)

2024-10-28 02:24 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
hashcode

2024-10-30 02:12 UTC, AYETATAPIN commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
done

2024-10-30 02:13 UTC, AYETATAPIN commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +        modCount++;
GOOOOOOOOOL

2024-10-30 02:13 UTC, AYETATAPIN commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
?

2024-10-30 02:20 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +    void hashTableTesting() throws IllegalAccessException {
разбей на отдельные тесты, не стоит всё тестировать в одном тесте, будет потом неудобно использовать эти тесты: 
 1. если упадёт первый assert дальше не будут проверяться тесты (в твоём текущем исполнении)
 2. если упадёт, надо ещё разбираться, где конкретно, не будет сразу видно, что упало

2024-10-30 02:20 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
криво сформулировала. Я имела ввиду тест, в котором одна хэш-таблица будет типов K1, V1, а вторая - K2, V2, и K1 != K2, V1 != V2

2024-10-30 02:22 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
согласно контракту equals , equals и hashcode должны быть согласованы:   если объекты равны, то и хэши должны быть равны. Реализация hashcode в Object не согласована с твоим equals

2024-10-31 03:13 UTC, AYETATAPIN commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +    void hashTableTesting() throws IllegalAccessException {
типо на каждый assert по метке @Test и отдельная функция?

2024-10-31 06:16 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +    void hashTableTesting() throws IllegalAccessException {
ага

2024-10-31 06:19 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +    void hashTableTesting() throws IllegalAccessException {
кстати не используй ключевое слово assert, используй assertTrue и тд
https://stackoverflow.com/questions/2966347/assert-vs-junit-assertions

2024-10-31 06:20 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +    void hashTableTesting() throws IllegalAccessException {
@AYETATAPIN

2024-11-01 02:29 UTC, AYETATAPIN commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
как я могу затестить функцию дефолтную для объекта в джаве?

2024-11-01 03:38 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
тебе нужно переопределить hashcode в своём классе

2024-11-03 15:25 UTC, galinabykova requested changes

2024-11-03 15:25 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +        assertTrue(Objects.equals(sampleHashTable.equals(differentTypeHashTable), false));
AssertFalse

2024-11-03 15:25 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +        assertTrue(Objects.equals(sampleHashTable.equals(smallHashTable), true));
AssertEquals

2024-11-03 15:25 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +    void hashTableTesting() throws IllegalAccessException {
разбей не на два теста, а на много маленьких, каждый из которых будет тестировать отдельную функциональность. Если нужно инициализировать каждый раз одну и ту же хэш-таблицу, используй Before each или что-то такое

2024-11-03 15:25 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/demidov/hashtable/HashTableTest.java
> +        assertTrue(Objects.equals(sampleHashTable.toString(), "{two : 2; one : 11}"));
используй наиболее уместный ассерт

2024-11-03 15:25 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +    public boolean equals(Object o) {
не увидела  hashcode

2024-11-04 12:37 UTC, galinabykova requested changes
нужно переопределить hashcode и reviewdog

2024-11-04 15:17 UTC, galinabykova approved these changes

2024-11-04 15:17 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/demidov/hashtable/HashTable.java
> +        return size;
это не очень хороший хэш, но контракту удовлетворяет,так что пойдёт)

2024-11-04 15:53 UTC, merged