Task_1_3_1
AYETATAPIN/OOP pull request #7
Opened 2024-11-05 18:02 UTC by AYETATAPIN

2024-11-06 02:30 UTC, galinabykova requested changes
Эта лаба сама по себе небольшая, но в ней много подводных камней, поэтому хорошо бы разобраться с хотя бы некоторыми особенностями в первую неделю. Для мягкого дедлайна сделай тест, доказывающий, что твой метод работает в ситуации, когда файл не влезает в память. Создай прямо в тесте большой файл, вызови метод и не забудь удалить файл в конце теста.

Для жёсткого дедлайна нужно будет как минимум написать тесты, покрывающие различные тестовые случаи (в том числе, когда вхождения строки пересекаются, например, ааааааааааа в аааааааааааааааааааааа). Эти тесты или хотя бы один из них лучше загружать как ресурс

2024-11-06 02:30 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            System.out.println(exception.getMessage());
мне кажется, лучше тут пробросить исключение дальше (Wrapping exception тут https://www.baeldung.com/java-wrapping-vs-rethrowing-exceptions)

2024-11-06 02:30 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            System.out.println(exception.getMessage());
так как по сути ты тут не знаешь ,что делать

2024-11-07 03:22 UTC, galinabykova reviewed
мягкий засчитан

2024-11-07 03:22 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +        }
файлик надо закрыть в конце

2024-11-07 03:22 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +        long OCCURENCES = 10000000;
нужно, чтобы файл не влезал в оперативную память твоего компьютера

2024-11-07 03:22 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +    public void initEach() throws IOException {
не поняла, как ты это используешь

2024-11-07 03:22 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +        List<Integer> result = SubStringFinder.myFind("input.txt", "boobies");
в этой лабе мы учимся работать с ресурсами. Ты тут используешь знание о том, где у тебя лежит твой файл, что в общем случае неверно (хотя я не понимаю, откуда файл вообще берётся, разве что из других тестов). Основная фишка ресурсов в том, что они являются частью сборки и попадают, например, в jar.

Посмотри, как сделано тут
https://sky.pro/wiki/java/poluchenie-puti-k-resursu-v-jar-fayle-java-resheniya-i-oshibki/
в статическом методе можно написать НазваниеКласса.class вместо getClass

2024-11-07 03:23 UTC, galinabykova requested changes
забыла запросить изменения

2024-11-08 06:17 UTC, AYETATAPIN commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +        long OCCURENCES = 10000000;
done

2024-11-08 06:17 UTC, AYETATAPIN commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +    public void initEach() throws IOException {
избежание дублирования кода

2024-11-08 06:25 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +    public void initEach() throws IOException {
а увидела, я почему-то пропустила использования переменной tempFile в коде

2024-11-08 06:52 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +        List<Integer> result = SubStringFinder.myFind("input.txt", "boobies");
в отличие от чтения обычного файла, ресурс будет храниться в сборке программы, поэтому тебе не нужно тащить его туда-сюда вместе со сборкой. И не нужно знать, в каком месте этот файл находится. Ресурсы очень часто нужны для десктопных приложений, я много с ними сталкивалась, и много новых студентов с ними косячило, когда только приходило на работу.

В целом, ты  бы мог создавать маленькие файлики, как большой, но они маленькие, нет причин их каждый раз пересоздавать, а мне нужно, чтобы вы поработали с ресурсами, я очень часто сталкивалась с ними на работе.

Также, пока будешь делать ресурсы, у тебя возникнут проблемы с твоей функцией (потому что в текущей версии она читает именно файлы, а не ресурсы), преодоление которых полезно для осознания иерархичности файловой системы Java.

2024-11-08 07:45 UTC, galinabykova requested changes
ресурсы

2024-11-08 07:45 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            throw new Exception("Error opening the file: " + exception.getMessage());
используй более специфичный тип исключений

2024-11-08 07:45 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
нужен ещё текст с какими-нибудь иероглифами

2024-11-13 03:31 UTC, AYETATAPIN commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            System.out.println(exception.getMessage());
done

2024-11-13 03:31 UTC, AYETATAPIN commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
> +        List<Integer> result = SubStringFinder.myFind("input.txt", "boobies");
done

2024-11-13 03:32 UTC, AYETATAPIN commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            throw new Exception("Error opening the file: " + exception.getMessage());
done

2024-11-13 03:32 UTC, AYETATAPIN commented on Task_1_3_1/src/test/java/ru/nsu/demidov/substring/SubStringFinderTest.java
done

2024-11-13 05:12 UTC, galinabykova requested changes

2024-11-13 05:12 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            throw new FileNotFoundException("Error opening the file: " + exception.getMessage());
хотелось бы именно wrapping, а не rethrow, то есть, чтобы у тебя создавалось исключение с причиной-старым исключением. Посмотри входной параметр конструктора cause
https://docs.oracle.com/javase/6/docs/api/java/lang/Throwable.html#Throwable(java.lang.String,%20java.lang.Throwable)

2024-11-14 04:42 UTC, galinabykova requested changes

2024-11-14 04:42 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            throw new FileNotFoundException().initCause(exception.getCause());
тебе надо в причине указывать не причину exception, а сам exception. И у исключения есть  конструктор с причиной

ещё мне непонятно, почему ты IOException заменяешь FileNotFoundException. Тут лучше создать свой класс исключений и бросать его

2024-11-14 05:18 UTC, AYETATAPIN commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            throw new FileNotFoundException("Error opening the file: " + exception.getMessage());
done

2024-11-14 05:50 UTC, galinabykova requested changes
reviewdog

2024-11-15 06:11 UTC, AYETATAPIN commented on Task_1_3_1/src/main/java/ru/nsu/demidov/substring/SubStringFinder.java
> +            throw new StreamCorruptedException().initCause(exception);
done

2024-11-15 06:15 UTC, galinabykova approved these changes

2024-11-15 16:45 UTC, merged